---
- name: Ensure Apt HTTPS transport is installed
  become: true
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Ensure GPG is installed
  become: true
  ansible.builtin.apt:
    name: gpg-agent
    state: present

- name: Add VSCode apt key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VSCode Apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: Install VSCode
  become: true
  ansible.builtin.apt:
    name: "{{ vscode_channel_map[vscode_channel].package_name }}"
    state: present
    update_cache: true

...
